env:
  browser: false
  commonjs: true
  es6: true
  jasmine: true
  jest: true
ext: '.js'
extends:
  - 'plugin:jasmine/recommended'
  - 'eslint:recommended'
  - 'airbnb'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: false
  sourceType: module
plugins:
  - jasmine
rules:
  camelcase: 0
  'arrow-body-style': 0
  'react/no-multi-comp': 0
  'react/require-extension': 0
  'class-methods-use-this': 0
  'no-underscore-dangle': 0
  'consistent-return': 0
  'no-multi-spaces': 0
  'import/newline-after-import': 0
  'jsx-a11y/anchor-has-content': 0
